# Generated by Django 4.1.3 on 2022-11-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                ("seats", models.IntegerField()),
                ("doors", models.IntegerField()),
                ("engine", models.CharField(max_length=100)),
            ],
        ),
    ]
